[secrets]
digitaloceanAPIKey = "apikey"
gamocosmUsername = "contact@example.org"
gamocosmPassword = "PaSsWoRd"

[servers.example]
name = "example"
id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
port = 25000
