[secrets]
digitaloceanAPIKey = "apikey"
gamocosmUsername = ""
gamocosmPassword = ""

[servers.example]
name = "example"
id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
port = 25565
onlinemode = true
